name: monitoring
description: "MBZ Toll Road Monitoring Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.8
  
  # Local Storage
  path_provider: ^2.1.2
  
  # HTTP & API
  http: ^1.1.0
  
  # State Management (optional)
  # provider: ^6.1.1
  
  # Image handling (for future camera integration)
  # image_picker: ^1.0.7
  
  # Location services (for GPS coordinates)
  # location: ^5.0.3
  # geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets (for future use)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts (for custom fonts if needed)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700

