name: monitoring
description: "MBZ Toll Road Monitoring Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.8
  
  # Database
  sqflite: ^2.3.0
  
  # Local Storage & File System
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # HTTP & API
  http: ^1.1.0
  
  # Date & Time utilities
  intl: ^0.18.1
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # Shared preferences
  shared_preferences: ^2.2.2
  
  # Image handling
  image_picker: ^1.0.7
  
  # Location services
  location: ^5.0.3
  geolocator: ^10.1.0
  

  
  # Permissions (Android/iOS only)
  permission_handler: ^11.1.0
  
  # File sharing
  share_plus: ^7.2.1
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true